# 🛒 Market Basket Analysis using Apriori Algorithm

## 📌 Objective
The goal of this project is to identify relationships between products frequently purchased together using transaction-level data.

Market Basket Analysis helps businesses understand customer buying behavior and uncover cross-selling opportunities.

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

## 📊 Dataset Overview

The dataset contains retail transaction data including:
- InvoiceNo (Transaction ID)
- Description (Product Name)
- Quantity (Number of items purchased)
- InvoiceDate (Transaction Date)
- CustomerID

Each row represents a product purchased within a transaction.

In [2]:
df = pd.read_excel("Online+Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## 🧹 Data Cleaning

Before analysis, the dataset was cleaned by:
- Removing missing product descriptions
- Filtering out negative quantities (returns)
- Ensuring correct data types for processing

This step ensures accurate and reliable results.

In [3]:
# Remove nulls
df = df.dropna(subset=['Description'])

In [4]:
# Remove negative/returns
df = df[df['Quantity'] > 0]

In [5]:
# Convert to string
df['InvoiceNo'] = df['InvoiceNo'].astype(str)

In [6]:
basket = (df
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum()
          .unstack()
          .fillna(0))

In [8]:
def encode(x):
    if x > 0:
        return 1
    return 0

basket = (basket > 0).astype(int)

In [9]:
frequent_items = apriori(basket, min_support=0.02, use_colnames=True)

C:\Users\DURGA DAMAI\anaconda3\envs\mba_project\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [10]:
rules = association_rules(frequent_items, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({PACK OF 72 RETROSPOT CAKE CASES}),frozenset({60 TEATIME FAIRY CAKE CASES}),0.065554,0.041120,0.022497,0.343182,8.345784,1.0,0.019801,1.459886,0.941926,0.267257,0.315015,0.445142
1,frozenset({60 TEATIME FAIRY CAKE CASES}),frozenset({PACK OF 72 RETROSPOT CAKE CASES}),0.041120,0.065554,0.022497,0.547101,8.345784,1.0,0.019801,2.063256,0.917924,0.267257,0.515329,0.445142
2,frozenset({ALARM CLOCK BAKELIKE PINK}),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.038886,0.048669,0.020759,0.533844,10.968864,1.0,0.018866,2.040800,0.945603,0.310781,0.509996,0.480187
3,frozenset({ALARM CLOCK BAKELIKE GREEN}),frozenset({ALARM CLOCK BAKELIKE PINK}),0.048669,0.038886,0.020759,0.426531,10.968864,1.0,0.018866,1.675965,0.955328,0.310781,0.403329,0.480187
4,frozenset({ALARM CLOCK BAKELIKE RED }),frozenset({ALARM CLOCK BAKELIKE GREEN}),0.052195,0.048669,0.031784,0.608944,12.511932,1.0,0.029244,2.432722,0.970744,0.460101,0.588938,0.631003

In [11]:
rules.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
160,"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",frozenset({PINK REGENCY TEACUP AND SAUCER}),0.038141,0.038041,0.026917,0.705729,18.551648,1.0,0.025466,3.268957,0.983612,0.546371,0.694092,0.706650
161,frozenset({PINK REGENCY TEACUP AND SAUCER}),"frozenset({GREEN REGENCY TEACUP AND SAUCER, RO...",0.038041,0.038141,0.026917,0.707572,18.551648,1.0,0.025466,3.289215,0.983510,0.546371,0.695976,0.706650
162,frozenset({GREEN REGENCY TEACUP AND SAUCER}),"frozenset({PINK REGENCY TEACUP AND SAUCER, ROS...",0.050407,0.029748,0.026917,0.533990,17.950627,1.0,0.025417,2.082042,0.994417,0.505597,0.519702,0.719416
159,"frozenset({PINK REGENCY TEACUP AND SAUCER, ROS...",frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.029748,0.050407,0.026917,0.904841,17.950627,1.0,0.025417,9.979054,0.973243,0.505597,0.899790,0.719416
24,frozenset({PINK REGENCY TEACUP AND SAUCER}),frozenset({GREEN REGENCY TEACUP AND SAUCER}),0.038041,0.050407,0.031436,0.826371,16.393893,1.0,0.029519,5.469083,0.976135,0.551394,0.817154,0.725008
25,frozenset({GREEN REGENCY TEACUP AND SAUCER}),frozenset({PINK REGENCY TEACUP AND SAUCER}),0.050407,0.038041,0.031436,0.623645,16.393893,1.0,0.029519,2.555990,0.988847,0.551394,0.608762,0.725008
158,"frozenset({PINK REGENCY TEACUP AND SAUCER, GRE...",frozenset({ROSES REGENCY TEACUP AND SAUCER }),0.031436,0.052940,0.026917,0.856240,16.173782,1.0,0.025253,6.587791,0.968621,0.468453,0.848204,0.682341
163,frozenset({ROSES REGENCY TEACUP AND SAUCER }),"frozenset({PINK REGENCY TEACUP AND SAUCER, GRE...",0.052940,0.031436,0.026917,0.508443,16.173782,1.0,0.025253,1.970399,0.990615,0.468453,0.492489,0.682341
23,frozenset({GARDENERS KNEELING PAD KEEP CALM }),frozenset({GARDENERS KNEELING PAD CUP OF TEA }),0.045342,0.037644,0.027116,0.598028,15.886413,1.0,0.025409,2.394090,0.981559,0.485333,0.582305,0.659173
22,frozenset({GARDENERS KNEELING PAD CUP OF TEA }),frozenset({GARDENERS KNEELING PAD KEEP CALM }),0.037644,0.045342,0.027116,0.720317,15.886413,1.0,0.025409,3.413354,0.973707,0.485333,0.707033,0.659173